#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const rootDir = path.resolve(__dirname, '..');
const mocksDir = path.join(rootDir, 'mocks');
const outputPath = path.join(__dirname, 'generated-from-mocks.mongosh.js');

function readJson(fileName) {
  const filePath = path.join(mocksDir, fileName);
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function uniqueById(items) {
  const seen = new Set();
  return items.filter((item) => {
    if (!item || !item._id) return false;
    if (seen.has(item._id)) return false;
    seen.add(item._id);
    return true;
  });
}

function normalizeData() {
  const home = readJson('home.json');
  const usuariosRaw = readJson('usuarios.json');
  const oportunidadesRaw = readJson('oportunidades.json');

  const usuarios = Array.isArray(usuariosRaw.usuarios) ? usuariosRaw.usuarios : [];
  const projetosFromHome = Array.isArray(home.projects) ? home.projects : [];
  const eventos = Array.isArray(home.events) ? home.events : [];
  const oportunidades = Array.isArray(oportunidadesRaw.opportunities) ? oportunidadesRaw.opportunities : [];

  const projetosFromOpp = oportunidades
    .map((opp) => opp.projeto)
    .filter(Boolean)
    .map((proj) => ({
      _id: proj._id || proj.id,
      title: proj.titulo,
      area: proj.area,
      unidadeResponsavel: proj.unidadeResponsavel,
      summary: proj.summary || proj.descricao,
      tags: proj.tags || [],
      status: proj.status,
      vagas: proj.vagas
    }));

  const projetos = uniqueById([
    ...projetosFromHome,
    ...projetosFromOpp
  ]);

  return { usuarios, projetos, eventos, oportunidades };
}

function buildMongoshSeed({ usuarios, projetos, eventos, oportunidades }) {
  return `// Auto-generated by seed/from-mocks.js\n// Do not edit manually. Regenerate from mocks.\n\nconst targetDb = 'extensao_unb';\nconst db = db.getSiblingDB(targetDb);\n\nprint(\`Seeding database: \${targetDb}\`);\n\ntry {\n  db.dropDatabase();\n  print('Dropped existing database');\n} catch (e) {\n  print(e);\n}\n\nconst usuarios = ${JSON.stringify(usuarios, null, 2)};\nconst projetos = ${JSON.stringify(projetos, null, 2)};\nconst eventos = ${JSON.stringify(eventos, null, 2)};\nconst oportunidades = ${JSON.stringify(oportunidades, null, 2)};\n\ndb.createCollection('usuarios');\ndb.createCollection('projetos');\ndb.createCollection('eventos');\ndb.createCollection('oportunidades');\n\nif (usuarios.length) db.usuarios.insertMany(usuarios);\nif (projetos.length) db.projetos.insertMany(projetos);\nif (eventos.length) db.eventos.insertMany(eventos);\nif (oportunidades.length) db.oportunidades.insertMany(oportunidades);\n\ndb.usuarios.createIndex({ email: 1 }, { unique: true });\ndb.projetos.createIndex({ tags: 1 });\ndb.projetos.createIndex({ status: 1 });\ndb.eventos.createIndex({ projectId: 1, startAt: 1 });\ndb.oportunidades.createIndex({ projetoId: 1, tipo: 1 });\ndb.oportunidades.createIndex({ projetoId: 1, status: 1 });\n\nprint('Indexes created.');\nprintjson({\n  usuarios: db.usuarios.countDocuments(),\n  projetos: db.projetos.countDocuments(),\n  eventos: db.eventos.countDocuments(),\n  oportunidades: db.oportunidades.countDocuments()\n});\nprint('Done.');\n`;
}

function main() {
  const shouldApply = process.argv.includes('--apply');

  const normalized = normalizeData();
  const script = buildMongoshSeed(normalized);
  fs.writeFileSync(outputPath, script, 'utf8');

  console.log(`Generated: ${path.relative(rootDir, outputPath)}`);

  if (!shouldApply) {
    console.log('Run with --apply to execute against Docker MongoDB.');
    return;
  }

  const mongoUser = process.env.MONGO_USER || 'meu_nome';
  const mongoPassword = process.env.MONGO_PASSWORD || 'minha_senha1_';
  const command = [
    'docker',
    'exec',
    '-i',
    'backend-mongo-1',
    'mongosh',
    '-u',
    mongoUser,
    '-p',
    mongoPassword,
    '--authenticationDatabase',
    'admin'
  ];

  console.log('Applying generated seed to MongoDB container...');
  const result = spawnSync('sudo', command, {
    input: script,
    stdio: ['pipe', 'inherit', 'inherit']
  });

  if (result.status !== 0) {
    process.exit(result.status || 1);
  }
}

main();
